---
- name: Install base packages
  hosts: kubernetes
  become: true
  gather_facts: true

  tasks:
    - name: Install base apt packages
      ansible.builtin.apt:
        pkg:
          - curl
          - vim
          - zsh
          - lm-sensors
          - tmux
          - htop

    - name: Install oh-my-zsh
      ansible.builtin.shell: |
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
      args:
        creates: /home/{{ ansible_user }}/.oh-my-zsh
