---
- name: Install k3s on servers
  hosts: kubernetes
  become: yes
  tasks:
    - name: Download and install k3s
      shell: curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Ensure k3s service is running
      service:
        name: k3s
        state: started
        enabled: yes