---
- name: Apt update and dist-upgrade
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Upgrade all packages (dist-upgrade)
      ansible.builtin.apt:
        upgrade: dist
